spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    models:
      suffix: .html
      path: classpath:templates/
    cache:
      enabled: true
      ttl:
        ms: 60000 # 60 seconds


